server:
  port: 8080

spring:
  application:
    name: productservice
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb
    username: premkumar
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: http://configserver:9296/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}