server:
  port: 9090

spring:
  application:
    name: APIGW
  cloud:
    gateway:
      routes:
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderservice
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productservice
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: paymentservice
          uri: lb://paymentservice
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentservice
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

okta:
  oauth2:
    issuer: https://dev-21709836.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa6vjkmae9r9nz3b5d7
    client-secret: UZ-iL8a08c056JKZwhoDQ1kxAECbdWuQdm1ttzCv
    scopes: openid, email, profile, offline_access

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true