server:
  port: 8081

spring:
  application:
    name: paymentservice
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: premkumar
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296